apiVersion: v1
kind: Service
metadata:
  name: projections
  namespace: projections
spec:
  type: ClusterIP
  selector:
    app: projections
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: memberlist
      protocol: TCP
      port: 7946
      targetPort: 7946
    - name: grpc
      protocol: TCP
      port: 9000
      targetPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: projections-headless
  namespace: projections
spec:
  clusterIP: None
  selector:
    app: projections
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
